# Generated by Django 4.0.1 on 2024-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('mobileNo', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
