# Generated by Django 4.0.1 on 2024-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApp', '0002_userdata_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobileNo',
            field=models.CharField(max_length=12),
        ),
    ]
